# Generated by Django 4.2.3 on 2023-12-04 01:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DrivelineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Модели ведущих мостов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Модели двигателей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FailureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': 'Узлы отказа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
                'verbose_name_plural': 'Модели техники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид технического обслуживания',
                'verbose_name_plural': 'Виды технического обслуживания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestorationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Способы восстановления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SteeringAxelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Модели управляемых мостов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Модели трансмиссий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceOrganization',
            fields=[
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('user_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № машины')),
                ('engine_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № двигателя')),
                ('transmission_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № трансмиссии')),
                ('driveline_model_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № ведущего моста')),
                ('steering_axel_model_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.CharField(max_length=20, unique=True, verbose_name='Договор поставки №, дата')),
                ('factory_delivery_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('end_user', models.CharField(max_length=50, unique=True, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=50, unique=True, verbose_name='Адрес поставки (эксплуатации)')),
                ('machine_configuration', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('buyer_client_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('driveline_model_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.drivelinemodel', verbose_name='Модель ведущего моста')),
                ('engine_model_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.enginemodel', verbose_name='Модель двигателя')),
                ('machine_model_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.machinemodel', verbose_name='Модель техники')),
                ('steering_axel_model_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.steeringaxelmodel', verbose_name='Модель управляемого')),
                ('transmission_model_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.transmissionmodel', verbose_name='Модель трансмиссии')),
                ('maintenance_organization_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.maintenanceorganization', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['factory_delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_hours', models.IntegerField(verbose_name='Наработка м/час')),
                ('work_order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказ-наряда')),
                ('work_order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_api.machine', verbose_name='Машина')),
                ('maintenance_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.maintenancetype', verbose_name='Вид ТО')),
                ('maintenance_organization_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.maintenanceorganization', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Техническое обслуживание',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_hours', models.IntegerField(verbose_name='Наработка м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('used_spare_parts', models.TextField(blank=True, verbose_name='Используемые запасные части')),
                ('restoration_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime_duration', models.IntegerField(verbose_name='Время простоя')),
                ('failure_component_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.failurecomponent', verbose_name='Узел отказа')),
                ('machine_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_api.machine', verbose_name='Машина')),
                ('restoration_method_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.restorationmethod', verbose_name='Способ восстановления')),
                ('maintenance_organization_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.maintenanceorganization', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['-failure_date'],
            },
        ),
    ]
