# Generated by Django 4.2.7 on 2023-12-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='driveline_model_fk',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='engine_model_fk',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='machine_model_fk',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='maintenance_organization_fk',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='steering_axel_model_fk',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='transmission_model_fk',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='machine_fk',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_organization_fk',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_type_fk',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
