# Generated by Django 4.2.3 on 2023-12-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='delivery_address',
            field=models.CharField(max_length=50, verbose_name='Адрес поставки (эксплуатации)'),
        ),
    ]
