# Generated by Django 4.2.7 on 2023-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivelineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Модели ведущих мостов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SteeringAxelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Модели управляемого моста',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='enginemodel',
            options={'ordering': ['name'], 'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Модели двигателей'},
        ),
        migrations.AlterModelOptions(
            name='machinemodel',
            options={'ordering': ['name'], 'verbose_name': 'Модель погрузчика', 'verbose_name_plural': 'Модели погрузчиков'},
        ),
        migrations.AlterModelOptions(
            name='transmissionmodel',
            options={'ordering': ['name'], 'verbose_name': 'Модель трансмиссии', 'verbose_name_plural': 'Модели трансмиссий'},
        ),
    ]
