# Generated by Django 4.2.7 on 2023-12-14 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silant_api', '0002_alter_machine_delivery_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-factory_delivery_date'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='steering_axel_model_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.steeringaxelmodel', verbose_name='Модель управляемого моста'),
        ),
    ]
