# Generated by Django 4.2.7 on 2023-12-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silant_api', '0002_drivelinemodel_steeringaxelmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': 'Узлы отказа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид технического обслуживания',
                'verbose_name_plural': 'Виды технического обслуживания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestorationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Способы восстановления',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='machinemodel',
            options={'ordering': ['name'], 'verbose_name': 'Модель техники', 'verbose_name_plural': 'Модели техники'},
        ),
        migrations.AlterModelOptions(
            name='steeringaxelmodel',
            options={'ordering': ['name'], 'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модели управляемых мостов'},
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № машины')),
                ('engine_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № двигателя')),
                ('transmission_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № трансмиссии')),
                ('engine_model_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.enginemodel')),
                ('machine_model_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.machinemodel')),
                ('transmission_model_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.transmissionmodel')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
                'ordering': ['engine_serial'],
            },
        ),
    ]
