# Generated by Django 4.2.7 on 2023-12-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant_api', '0003_failurecomponent_maintenanceorganization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
