# Generated by Django 4.2.7 on 2023-12-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant_api', '0005_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
