# Generated by Django 4.2.7 on 2023-12-02 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silant_api', '0006_delete_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № машины')),
                ('engine_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № двигателя')),
                ('transmission_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № трансмиссии')),
                ('driveline_model_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № ведущего моста')),
                ('steering_axel_model_serial', models.CharField(max_length=20, unique=True, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.CharField(max_length=20, unique=True, verbose_name='Договор поставки №, дата')),
                ('factory_delivery_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('end_user', models.CharField(max_length=50, unique=True, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=50, unique=True, verbose_name='Адрес поставки (эксплуатации)')),
                ('machine_configuration', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('buyer_client', models.CharField(max_length=50, unique=True, verbose_name='Клиент')),
                ('driveline_model_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.drivelinemodel')),
                ('engine_model_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.enginemodel')),
                ('machine_model_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.machinemodel')),
                ('maintenance_organization_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.maintenanceorganization')),
                ('steering_axel_model_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.steeringaxelmodel')),
                ('transmission_model_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_api.transmissionmodel')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['factory_delivery_date'],
            },
        ),
    ]
